### ISSUE TITLE
Mapping KEY_CONTEXT_MENU does not work

### ISSUE THREAD

**Issue by 73** [maricn/interception-vimproved#15]
Hey there,

thank you very much for making this public.
I have a problem mapping `KEY_CONTEXT_MENU`. I try something like:

```yaml
- intercept: KEY_PRT_SC
  onhold: KEY_RIGHTALT
  ontap: KEY_CONTEXT_MENU
```

The `onhold` setting works, but the `ontap` setting does not take. 
What shall I do to provide you with the relevant information? Are you able to reproduce the behavior?
